#!/bin/sh

scriptDir="$(cd "$(dirname "$0")"; pwd)"

cd $scriptDir

find . \( -name .DS_Store \) -depth -exec rm {} \; 2> /dev/null

\rm -r .vscode api/__pycache__ node_modules > /dev/null 2>&1

cd - > /dev/null
